
### REGISTER FOR A NEW USER 
POST http://localhost:3002/Register
Content-Type: application/json

{
    "username": "Jose",
    "password": "jose123",
    "mobileNumber": "5678789879",
    "country": "US",
    "city": "San Jose",
    "pinCode": "600071",
    "role": "Admin"
}


### LOGIN API
POST http://localhost:3002/login
Content-Type: application/json

{
    "username": "Abhilash",
    "password": "abhi123"
}

### CREATING A NEW EVENT
POST http://localhost:3002/events
Content-Type: application/json

{
    "name": "Joe",
    "date": "23-6-2021",
    "location": "Germany",
    "description": "Weather is the state of the atmosphere, including temperature, atmospheric pressure, wind, humidity, precipitation, and cloud cover. It differs from climate, which is all weather conditions for a particular location averaged over about 30 years"
}

### RETRIVE THE DATA API
GET http://localhost:3002/events

### UPDATE EVENT API
PUT http://localhost:3002/events/1
Content-Type: application/json

{
    "name": "Joe Root",
    "date": "4-5-2023",
    "location": "delhi",
    "description": "Event updation process"
}


### DELETE EVENT API
DELETE http://localhost:3002/events/3

### get_sessions data from the sessions table
GET http://localhost:3002/sessions


### get the data using open weather api 
GET http://localhost:3002/weatherDetails/new york
